"""Publish a generated asset into the main site repo as a permanent banner.

Owner-only. Takes a tool-generated asset URL (must be from OUR Spaces bucket),
downloads the bytes, and commits them to the site repo at
public/img/banners/<slug>.png via the GitHub Contents API — so the image is
served by the site's own CDN and never expires (unlike the 7-day Spaces TTL).

Returns the ready-to-paste frontmatter snippet.
"""
from __future__ import annotations

import base64
import re
from urllib.parse import urlparse

import requests
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

import config
from auth import require_owner

router = APIRouter()


class BannerRequest(BaseModel):
    url: str           # CDN/Spaces URL returned by a generate call
    name: str          # desired slug, e.g. "ai-economic-trap"
    alt: str = ""


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-") or "banner"


def _is_our_asset(url: str) -> bool:
    """Only fetch from our own Spaces bucket (origin or CDN) — owner-gated, but
    still refuse arbitrary URLs so this can't be turned into a commit-anything."""
    host = urlparse(url).hostname or ""
    origin_host = config.DO_SPACES_ENDPOINT.replace("https://", "").split("/")[0]
    allowed = {
        f"{config.DO_SPACES_BUCKET}.{origin_host}",
        f"{config.DO_SPACES_BUCKET}.{config.DO_SPACES_REGION}.cdn.digitaloceanspaces.com",
    }
    if config.DO_SPACES_CDN_BASE:
        allowed.add(urlparse(config.DO_SPACES_CDN_BASE).hostname or "")
    return host in allowed


@router.post("/banner", dependencies=[Depends(require_owner)])
def publish_banner(req: BannerRequest):
    if not config.github_configured():
        raise HTTPException(503, "publishing not configured (SITE_GITHUB_TOKEN/SITE_REPO missing)")
    if not _is_our_asset(req.url):
        raise HTTPException(400, "url must be an asset generated by this tool")

    # 1. fetch the asset bytes
    a = requests.get(req.url, timeout=20)
    if not a.ok:
        raise HTTPException(400, f"could not fetch asset ({a.status_code})")

    slug = _slug(req.name)
    path = f"{config.BANNER_DIR}/{slug}.png"
    api = f"https://api.github.com/repos/{config.SITE_REPO}/contents/{path}"
    headers = {
        "Authorization": f"Bearer {config.SITE_GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
    }

    # 2. if the path already exists, GitHub needs its blob sha to overwrite
    sha = None
    head = requests.get(api, headers=headers, params={"ref": config.SITE_BRANCH}, timeout=20)
    if head.status_code == 200:
        sha = head.json().get("sha")

    body = {
        "message": f"Add banner: {slug}",
        "content": base64.b64encode(a.content).decode(),
        "branch": config.SITE_BRANCH,
    }
    if sha:
        body["sha"] = sha

    put = requests.put(api, headers=headers, json=body, timeout=30)
    if not put.ok:
        raise HTTPException(502, f"GitHub commit failed ({put.status_code}): {put.text[:200]}")

    # public/ is served at the site root → /img/banners/<slug>.png
    public_path = "/" + path.split("public/", 1)[-1] if "public/" in path else "/" + path
    alt = req.alt.strip() or "Generated word-art banner"
    return {
        "path": public_path,
        "snippet": f'coverImage: "{public_path}"\ncoverAlt: "{alt}"',
        "commit_url": (put.json().get("commit") or {}).get("html_url"),
    }
